### ISSUE TITLE
Questions for assemble_design.py script

### ISSUE THREAD

**Issue by yiranzhimo** [emdann/ST_simulation#7]
Dear Emma,

Thank you for your work. Recently, I have been working on a project that needs to simulate an ST dataset from scRNA-seq data.

Your work truly inspires me. But I have some questions.

For the file assemble_design.py, the code is shown below.
### First question
**When calculating the value of sigma, why is it divided by 0.3?** 
```
mean_unif = round((tot_spots / 100) * percent_uniform)
mean_sparse = round((tot_spots / 100) * percent_sparse)
sigma_unif = np.sqrt(mean_unif / 0.3)
sigma_sparse = np.sqrt(mean_sparse / 0.3)
```
### Second question
**Why choose gamma distribution to illustrate characteristics?**
```
sigma_low = np.sqrt(mean_low / 2)
sigma_high = np.sqrt(mean_high / 2)
shape_low = mean_low ** 2 / sigma_low ** 2
scale_low = sigma_low ** 2 / mean_low
shape_high = mean_high ** 2 / sigma_high ** 2
scale_high = sigma_high ** 2 / mean_high
```
I know this repository was established four years ago. I would be very grateful if I could receive your reply.
Looking forward to it.

**Comment by emdann** [comment]
Hi @yiranzhimo, glad to hear you found this code useful! As you noted, this is rather old code and it was used to make benchmarks in the first version of the [cell2location paper](https://www.nature.com/articles/s41587-021-01139-4). For a refined version of this code, with optimized parameters I recommend checking out [this script](https://github.com/vitkl/cell2location_paper/blob/master/notebooks/benchmarking/synthetic_data_construction_improved_real_mg.ipynb) (and the full simulation process is described in depth in the paper [supplementary materials](https://static-content.springer.com/esm/art%3A10.1038%2Fs41587-021-01139-4/MediaObjects/41587_2021_1139_MOESM1_ESM.pdf)). 

Please note that there are more specialized tools for simulation of spatial transcriptomics data that you might find inspiring, such as those from [Baker et al](https://www.nature.com/articles/s41592-023-01766-6) and [Bost et al.](https://www.nature.com/articles/s41592-022-01692-z).
